### ISSUE TITLE
Investigate upgrading to styled-components v2!

### ISSUE THREAD

**Issue by rgdelato** [rgdelato/styled-classnames#4]
Hopefully, this upgrade should be a big win for speed and bundle size since styled-components v2 has switched from using PostCSS to using stylis as their runtime CSS parser.

**Comment by noxecane** [comment]
Is there any way I could help with testing this update

**Comment by rgdelato** [comment]
@noxecane Unfortunately, there's no update to test since I haven't gotten around to doing this just yet. Also, v2 is a huge change for styled-components, so I wanted to give v2 some time for the dust to settle anyway.

**Comment by noxecane** [comment]
Ok...Even looking at their changelog scared me off

**Comment by rgdelato** [comment]
@noxecane Okay, `styled-classnames` v2.2.1 should now be upgraded to use the new `styled-components` v2. Give it a try and let me know if there are any issues!

**Comment by noxecane** [comment]
Ok
